#???????????????????root????????demo????????????
spring:
  datasource:
    username: root
    password: hsp
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver

#mybatis??resources?mapper?????xml??
mybatis:
  mapper-locations: classpath:mapper/*.xml

#???8081
server:
  port: 8081
